pipeline {

    agent {
        label 'docker-agent'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test') {
            steps {
                sh '''
                    cd 02-jenkins-docker-sonarqube-cicd/application
                    ./test.sh
                '''
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonarqube') {
                    script {
                        def scannerHome = tool 'SonarScanner'

                        sh """
                            cd 02-jenkins-docker-sonarqube-cicd/application
                            ${scannerHome}/bin/sonar-scanner
                        """
                    }
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                    cd 02-jenkins-docker-sonarqube-cicd/application
                    docker build -t devops-cicd-demo:latest .
                '''
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-credentials',
                        usernameVariable: 'DOCKER_USERNAME',
                        passwordVariable: 'DOCKER_PASSWORD'
                    )
                ]) {
                    sh '''
                        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

                        docker tag devops-cicd-demo:latest \
                            $DOCKER_USERNAME/devops-cicd-demo:latest

                        docker push \
                            $DOCKER_USERNAME/devops-cicd-demo:latest

                        docker logout
                    '''
                }
            }
        }

    }
}

